//
//  NotificationConsts.swift
//  pengxiang_travel
//
//  Created by danny on 2020/9/27.
//  Copyright © 2020 udianbus. All rights reserved.
//

import Foundation

/// 新增或修改订单信息成功的通知
let NOTIFICATION_CREATE_OR_UPDATE_ORDER_SUCEESS = "NOTIFICATION_CREATE_OR_UPDATE_ORDER_SUCEESS"

/// 取消订单信息成功的通知 取消在当前也更新 其他页面不更新
let NOTIFICATION_CANCEL_ORDER_SUCEESS = "NOTIFICATION_CANCEL_ORDER_SUCEESS"

/// tab切换索引
let NOTIFICATION_TAB_CHANGE_NOTIFICATION = "NOTIFICATION_TAB_CHANGE_NOTIFICATION"

/// 拨打客服电话的通知
let NOTIFICATION_CALL_CONTACT_SERVICE_NOTIFICATION = "NOTIFICATION_CALL_CONTACT_SERVICE_NOTIFICATION"

/// 获取司机待派车订单成功
let NOTIFICATION_GET_WAITINGTO_DISPATCH_BUS_COUNT_NOTIFICATION = "NOTIFICATION_GET_WAITINGTO_DISPATCH_BUS_COUNT_NOTIFICATION"
